version: "3"

services:
  cbc-app:
    build: .
    user: node
    container_name: cbc_api
    tty: true
    stdin_open: true
    image: node:16.4
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOSTNAME: db
      DB_NAME: cbc_api
      DB_PORT: 3306

  db:
    container_name: cbc_db
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
